---
- name: Validate nginx configuration
  ansible.builtin.command:
    cmd: nginx -t
  changed_when: false

- name: Reload nginx
  ansible.builtin.service:
    name: "{{ web_service_name }}"
    state: reloaded
